package com.company.suralarMenu;

import org.telegram.telegrambots.meta.api.methods.ParseMode;
import org.telegram.telegrambots.meta.api.methods.send.SendMessage;
import org.telegram.telegrambots.meta.api.objects.Message;
import org.telegram.telegrambots.meta.api.objects.replykeyboard.ReplyKeyboardMarkup;
import org.telegram.telegrambots.meta.api.objects.replykeyboard.buttons.KeyboardRow;

import java.util.ArrayList;
import java.util.List;

public class SuralarMenu {

    public SendMessage sendTextMessageMenu(Message message){
        SendMessage sendMessage = new SendMessage();
        sendMessage.setText("Qaysi surani tanlaysi: ");
        sendMessage.setParseMode(ParseMode.MARKDOWN);
        sendMessage.setChatId(String.valueOf(message.getChatId()));

        ReplyKeyboardMarkup replyKeyboardMarkup = new ReplyKeyboardMarkup();
        replyKeyboardMarkup.setResizeKeyboard(true);
        replyKeyboardMarkup.setSelective(true);
        List<KeyboardRow> keyboardRowList = new ArrayList<>();
        KeyboardRow keyboardRow1 = new KeyboardRow();
        KeyboardRow keyboardRow2 = new KeyboardRow();
        KeyboardRow keyboardRow3 = new KeyboardRow();
        KeyboardRow keyboardRow4 = new KeyboardRow();
        KeyboardRow keyboardRow5 = new KeyboardRow();
        KeyboardRow keyboardRow6 = new KeyboardRow();
        KeyboardRow keyboardRow7 = new KeyboardRow();
        KeyboardRow keyboardRow8 = new KeyboardRow();
        KeyboardRow keyboardRow9 = new KeyboardRow();
        KeyboardRow keyboardRow10 = new KeyboardRow();
        KeyboardRow keyboardRow11 = new KeyboardRow();
        KeyboardRow keyboardRow12 = new KeyboardRow();
        KeyboardRow keyboardRow13 = new KeyboardRow();
        KeyboardRow keyboardRow14 = new KeyboardRow();
        KeyboardRow keyboardRow15 = new KeyboardRow();
        KeyboardRow keyboardRow16 = new KeyboardRow();
        KeyboardRow keyboardRow17 = new KeyboardRow();
        KeyboardRow keyboardRow18 = new KeyboardRow();
        KeyboardRow keyboardRow19 = new KeyboardRow();
        KeyboardRow keyboardRow20 = new KeyboardRow();
        KeyboardRow keyboardRow21 = new KeyboardRow();
        KeyboardRow keyboardRow22 = new KeyboardRow();
        KeyboardRow keyboardRow23 = new KeyboardRow();
        KeyboardRow keyboardRow24 = new KeyboardRow();
        KeyboardRow keyboardRow25 = new KeyboardRow();
        KeyboardRow keyboardRow26 = new KeyboardRow();
        KeyboardRow keyboardRow27 = new KeyboardRow();
        KeyboardRow keyboardRow28 = new KeyboardRow();
        KeyboardRow keyboardRow29 = new KeyboardRow();
        keyboardRow1.add("Fotiha");
        keyboardRow1.add("Baqara");
        keyboardRow1.add("Oli Imron");
        keyboardRow1.add("Niso");
        keyboardRow2.add("Moida");
        keyboardRow2.add("An'om");
        keyboardRow2.add("A'rof");
        keyboardRow2.add("Anfol");
        keyboardRow3.add("Tavba");
        keyboardRow3.add("Yunus");
        keyboardRow3.add("Hud");
        keyboardRow3.add("Yusuf");
        keyboardRow4.add("Ra'd");
        keyboardRow4.add("Ibrohim");
        keyboardRow4.add("Hijr");
        keyboardRow4.add("Nahl");
        keyboardRow5.add("Isro");
        keyboardRow5.add("Kahf");
        keyboardRow5.add("Maryam");
        keyboardRow5.add("Toha");
        keyboardRow6.add("Anbiyo");
        keyboardRow6.add("Haj");
        keyboardRow6.add("Mu'minun");
        keyboardRow6.add("Nur");
        keyboardRow7.add("Furqon");
        keyboardRow7.add("Shu'aro");
        keyboardRow7.add("Naml");
        keyboardRow7.add("Qasas");
        keyboardRow8.add("Ankabut");
        keyboardRow8.add("Rum");
        keyboardRow8.add("Luqmon");
        keyboardRow8.add("Sajda");
        keyboardRow9.add("Saba'");
        keyboardRow9.add("Fotir");
        keyboardRow9.add("Yosin");
        keyboardRow9.add("Soffat");
        keyboardRow10.add("Sod");
        keyboardRow10.add("Zumar");
        keyboardRow10.add("G'ofir");
        keyboardRow10.add("Fassilat");
        keyboardRow11.add("Sho'ro");
        keyboardRow11.add("Zuhruf");
        keyboardRow11.add("Duxon");
        keyboardRow11.add("Josiya");
        keyboardRow12.add("Ahqof");
        keyboardRow12.add("Muhammad");
        keyboardRow12.add("Fath");
        keyboardRow12.add("Hujurot");
        keyboardRow13.add("Qof");
        keyboardRow13.add("Zoriyot");
        keyboardRow13.add("Tur");
        keyboardRow13.add("Najm");
        keyboardRow14.add("Qamar");
        keyboardRow14.add("Rahmon");
        keyboardRow14.add("Voqea");
        keyboardRow14.add("Hadid");
        keyboardRow15.add("Mujadala");
        keyboardRow15.add("Hashr");
        keyboardRow15.add("Mumtahana");
        keyboardRow15.add("Sof");
        keyboardRow16.add("Jum'a");
        keyboardRow16.add("Munofiqun");
        keyboardRow16.add("Tag'obun");
        keyboardRow16.add("Taloq");
        keyboardRow17.add("Tahrim");
        keyboardRow17.add("Mulk");
        keyboardRow17.add("Qalam");
        keyboardRow17.add("Maorij");
        keyboardRow18.add("Nuh");
        keyboardRow18.add("Jin");
        keyboardRow18.add("Muzzammil");
        keyboardRow18.add("Muddassir");
        keyboardRow19.add("Qiyomat");
        keyboardRow19.add("Inson");
        keyboardRow19.add("Mursalot");
        keyboardRow19.add("Naba'");
        keyboardRow20.add("Nazi'at");
        keyboardRow20.add("Abasa");
        keyboardRow20.add("Takvir");
        keyboardRow20.add("Intifot");
        keyboardRow21.add("Mutoffifin");
        keyboardRow21.add("Inshiqoq");
        keyboardRow21.add("Buruj");
        keyboardRow21.add("Toriq");
        keyboardRow22.add("A'lo");
        keyboardRow22.add("G'oshiya");
        keyboardRow22.add("Fajr");
        keyboardRow22.add("Balad");
        keyboardRow23.add("Shams");
        keyboardRow23.add("Layl");
        keyboardRow23.add("Zuho");
        keyboardRow23.add("Sharh");
        keyboardRow24.add("Tiyn");
        keyboardRow24.add("Alaq");
        keyboardRow24.add("Qadr");
        keyboardRow24.add("Bayyina");
        keyboardRow25.add("Zalzala");
        keyboardRow25.add("Adiyat");
        keyboardRow25.add("Qoria");
        keyboardRow25.add("Takasur");
        keyboardRow26.add("Asr");
        keyboardRow26.add("Humaza");
        keyboardRow26.add("Fil");
        keyboardRow26.add("Quraysh");
        keyboardRow27.add("Moun");
        keyboardRow27.add("Kavsar");
        keyboardRow27.add("Kofirun");
        keyboardRow27.add("Nasr");
        keyboardRow28.add("Masad");
        keyboardRow28.add("Ixlos");
        keyboardRow28.add("Falaq");
        keyboardRow28.add("Nos");
        keyboardRow29.add("\uD83D\uDD19 Ortga");
        keyboardRowList.add(keyboardRow1);
        keyboardRowList.add(keyboardRow2);
        keyboardRowList.add(keyboardRow3);
        keyboardRowList.add(keyboardRow4);
        keyboardRowList.add(keyboardRow5);
        keyboardRowList.add(keyboardRow6);
        keyboardRowList.add(keyboardRow7);
        keyboardRowList.add(keyboardRow8);
        keyboardRowList.add(keyboardRow9);
        keyboardRowList.add(keyboardRow10);
        keyboardRowList.add(keyboardRow11);
        keyboardRowList.add(keyboardRow12);
        keyboardRowList.add(keyboardRow13);
        keyboardRowList.add(keyboardRow14);
        keyboardRowList.add(keyboardRow15);
        keyboardRowList.add(keyboardRow16);
        keyboardRowList.add(keyboardRow17);
        keyboardRowList.add(keyboardRow18);
        keyboardRowList.add(keyboardRow19);
        keyboardRowList.add(keyboardRow20);
        keyboardRowList.add(keyboardRow21);
        keyboardRowList.add(keyboardRow22);
        keyboardRowList.add(keyboardRow23);
        keyboardRowList.add(keyboardRow24);
        keyboardRowList.add(keyboardRow25);
        keyboardRowList.add(keyboardRow26);
        keyboardRowList.add(keyboardRow27);
        keyboardRowList.add(keyboardRow28);
        keyboardRowList.add(keyboardRow29);
        replyKeyboardMarkup.setKeyboard(keyboardRowList);
        sendMessage.setReplyMarkup(replyKeyboardMarkup);
        return sendMessage;
    }
}
